let images = ["images/fighters/banjo_and_kazooie.webp", "images/fighters/dark_pit.webp", "images/fighters/hero.webp", "images/fighters/king_k_rool.webp", "images/fighters/mega_man.webp", "images/fighters/peach.webp", "images/fighters/robin.webp", "images/fighters/sonic.webp", "images/fighters/zelda.webp", "images/fighters/bayonetta.webp", "images/fighters/dark_samus.webp", "images/fighters/ice_climbers.webp", "images/fighters/kirby.webp", "images/fighters/meta_knight.webp", "images/fighters/pichu.webp", "images/fighters/rosalina_and_luma.webp", "images/fighters/steve.webp", "images/fighters/zero_suit_samus.webp", "images/fighters/bowser.webp", "images/fighters/diddy_kong.webp", "images/fighters/ike.webp", "images/fighters/link.webp", "images/fighters/mewtwo.webp", "images/fighters/pikachu.webp", "images/fighters/roy.webp", "images/fighters/terry.webp", "images/fighters/bowser_jr.webp", "images/fighters/donkey_kong.webp", "images/fighters/incineroar.webp", "images/fighters/little_mac.webp", "images/fighters/mii_fighters.webp", "images/fighters/piranha_plant.webp", "images/fighters/ryu.webp", "images/fighters/toon_link.webp", "images/fighters/byleth.webp", "images/fighters/dr_mario.webp", "images/fighters/inkling.webp", "images/fighters/lucario.webp", "images/fighters/min_min.webp", "images/fighters/pit.webp", "images/fighters/samus.webp", "images/fighters/villager.webp", "images/fighters/captain_falcon.webp", "images/fighters/duck_hunt.webp", "images/fighters/isabelle.webp", "images/fighters/lucas.webp", "images/fighters/mr_game_and_watch.webp", "images/fighters/pokemon_trainer.webp", "images/fighters/sephiroth.webp", "images/fighters/wario.webp", "images/fighters/chrom.webp", "images/fighters/falco.webp", "images/fighters/jigglypuff.webp", "images/fighters/lucina.webp", "images/fighters/ness.webp", "images/fighters/pyra_mythra.webp", "images/fighters/sheik.webp", "images/fighters/wii_fit_trainer.webp", "images/fighters/cloud.webp", "images/fighters/fox.webp", "images/fighters/joker.webp", "images/fighters/luigi.webp", "images/fighters/olimar.webp", "images/fighters/richter.webp", "images/fighters/shulk.webp", "images/fighters/wolf.webp", "images/fighters/corrin.webp", "images/fighters/ganondorf.webp", "images/fighters/ken.webp", "images/fighters/mario.webp", "images/fighters/pac_man.webp", "images/fighters/ridley.webp", "images/fighters/simon.webp", "images/fighters/yoshi.webp", "images/fighters/daisy.webp", "images/fighters/greninja.webp", "images/fighters/king_dedede.webp", "images/fighters/marth.webp", "images/fighters/palutena.webp", "images/fighters/rob.webp", "images/fighters/snake.webp", "images/fighters/young_link.webp", "images/fighters/kazuya.webp", "images/fighters/sora.webp"]
let sounds = ["sounds/announcer_banjo_and_kazooie.wav", "sounds/announcer_dr_mario.wav", "sounds/announcer_ken.wav", "sounds/announcer_mewtwo.wav", "sounds/announcer_richter.wav", "sounds/announcer_steve.wav", "sounds/announcer_bayonetta.wav", "sounds/announcer_duck_hunt.wav", "sounds/announcer_king_dedede.wav", "sounds/announcer_mii.wav", "sounds/announcer_ridley.wav", "sounds/announcer_terry.wav", "sounds/announcer_bowser.wav", "sounds/announcer_falco.wav", "sounds/announcer_king_k_rool.wav", "sounds/announcer_min_min.wav", "sounds/announcer_rob.wav", "sounds/announcer_toon_link.wav", "sounds/announcer_bowser_jr.wav", "sounds/announcer_fox.wav", "sounds/announcer_kirby.wav", "sounds/announcer_mr_game_and_watch.wav", "sounds/announcer_robin.wav", "sounds/announcer_villager.wav", "sounds/announcer_byleth.wav", "sounds/announcer_ganondorf.wav", "sounds/announcer_link.wav", "sounds/announcer_ness.wav", "sounds/announcer_rosalina_and_luma.wav", "sounds/announcer_wario.wav", "sounds/announcer_captain_falcon.wav", "sounds/announcer_greninja.wav", "sounds/announcer_little_mac.wav", "sounds/announcer_olimar.wav", "sounds/announcer_roy.wav", "sounds/announcer_wii_fit_trainer.wav", "sounds/announcer_chrom.wav", "sounds/announcer_hero.wav", "sounds/announcer_lucario.wav", "sounds/announcer_pac_man.wav", "sounds/announcer_ryu.wav", "sounds/announcer_wolf.wav", "sounds/announcer_cloud.wav", "sounds/announcer_ice_climbers.wav", "sounds/announcer_lucas.wav", "sounds/announcer_palutena.wav", "sounds/announcer_samus.wav", "sounds/announcer_yoshi.wav", "sounds/announcer_corrin.wav", "sounds/announcer_ike.wav", "sounds/announcer_lucina.wav", "sounds/announcer_peach.wav", "sounds/announcer_sephiroth.wav", "sounds/announcer_young_link.wav", "sounds/announcer_daisy.wav", "sounds/announcer_incineroar.wav", "sounds/announcer_luigi.wav", "sounds/announcer_pichu.wav", "sounds/announcer_sheik.wav", "sounds/announcer_zelda.wav", "sounds/announcer_dark_pit.wav", "sounds/announcer_inkling.wav", "sounds/announcer_mario.wav", "sounds/announcer_pikachu.wav", "sounds/announcer_shulk.wav", "sounds/announcer_zero_suit_samus.wav", "sounds/announcer_dark_samus.wav", "sounds/announcer_isabelle.wav", "sounds/announcer_marth.wav", "sounds/announcer_piranha_plant.wav", "sounds/announcer_simon.wav", "sounds/se_matchup_spritsboad.wav", "sounds/announcer_diddy_kong.wav", "sounds/announcer_jigglypuff.wav", "sounds/announcer_mega_man.wav", "sounds/announcer_pit.wav", "sounds/announcer_snake.wav", "sounds/announcer_donkey_kong.wav", "sounds/announcer_joker.wav", "sounds/announcer_meta_knight.wav", "sounds/announcer_pokemon_trainer.wav", "sounds/announcer_sonic.wav", "sounds/announcer_kazuya.wav", "sounds/announcer_sora.wav"];
let scripts = ["scripts/fighter.js", "scripts/script.js"];

self.addEventListener('install', e => {
    e.waitUntil(
        caches.open('bright-smash').then(cache => {
            return cache.addAll([
                "index.html",
                "fighters.json",
                ...images,
                ...sounds,
                ...scripts
            ]);
        })
    );
});
self.addEventListener('fetch', e => {
    // console.log(e.request.url);
    e.respondWith(
        caches.match(e.request).then(response => {
            return response || fetch(e.request);
        })
    );
});
