let images = ["images/banjo_and_kazooie.webp", "images/dark_pit.webp", "images/hero.webp", "images/king_k_rool.webp", "images/mega_man.webp", "images/peach.webp", "images/robin.webp", "images/sonic.webp", "images/zelda.webp", "images/bayonetta.webp", "images/dark_samus.webp", "images/ice_climbers.webp", "images/kirby.webp", "images/meta_knight.webp", "images/pichu.webp", "images/rosalina_and_luma.webp", "images/steve.webp", "images/zero_suit_samus.webp", "images/bowser.webp", "images/diddy_kong.webp", "images/ike.webp", "images/link.webp", "images/mewtwo.webp", "images/pikachu.webp", "images/roy.webp", "images/terry.webp", "images/bowser_jr.webp", "images/donkey_kong.webp", "images/incineroar.webp", "images/little_mac.webp", "images/mii_fighters.webp", "images/piranha_plant.webp", "images/ryu.webp", "images/toon_link.webp", "images/byleth.webp", "images/dr_mario.webp", "images/inkling.webp", "images/lucario.webp", "images/min_min.webp", "images/pit.webp", "images/samus.webp", "images/villager.webp", "images/captain_falcon.webp", "images/duck_hunt.webp", "images/isabelle.webp", "images/lucas.webp", "images/mr_game_and_watch.webp", "images/pokemon_trainer.webp", "images/sephiroth.webp", "images/wario.webp", "images/chrom.webp", "images/falco.webp", "images/jigglypuff.webp", "images/lucina.webp", "images/ness.webp", "images/pyra_mythra.webp", "images/sheik.webp", "images/wii_fit_trainer.webp", "images/cloud.webp", "images/fox.webp", "images/joker.webp", "images/luigi.webp", "images/olimar.webp", "images/richter.webp", "images/shulk.webp", "images/wolf.webp", "images/corrin.webp", "images/ganondorf.webp", "images/ken.webp", "images/mario.webp", "images/pac_man.webp", "images/ridley.webp", "images/simon.webp", "images/yoshi.webp", "images/daisy.webp", "images/greninja.webp", "images/king_dedede.webp", "images/marth.webp", "images/palutena.webp", "images/rob.webp", "images/snake.webp", "images/young_link.webp"]
let sounds = ["sounds/announcer_banjo_and_kazooie.wav", "sounds/announcer_dr_mario.wav", "sounds/announcer_ken.wav", "sounds/announcer_mewtwo.wav", "sounds/announcer_richter.wav", "sounds/announcer_steve.wav", "sounds/announcer_bayonetta.wav", "sounds/announcer_duck_hunt.wav", "sounds/announcer_king_dedede.wav", "sounds/announcer_mii.wav", "sounds/announcer_ridley.wav", "sounds/announcer_terry.wav", "sounds/announcer_bowser.wav", "sounds/announcer_falco.wav", "sounds/announcer_king_k_rool.wav", "sounds/announcer_min_min.wav", "sounds/announcer_rob.wav", "sounds/announcer_toon_link.wav", "sounds/announcer_bowser_jr.wav", "sounds/announcer_fox.wav", "sounds/announcer_kirby.wav", "sounds/announcer_mr_game_and_watch.wav", "sounds/announcer_robin.wav", "sounds/announcer_villager.wav", "sounds/announcer_byleth.wav", "sounds/announcer_ganondorf.wav", "sounds/announcer_link.wav", "sounds/announcer_ness.wav", "sounds/announcer_rosalina_and_luma.wav", "sounds/announcer_wario.wav", "sounds/announcer_captain_falcon.wav", "sounds/announcer_greninja.wav", "sounds/announcer_little_mac.wav", "sounds/announcer_olimar.wav", "sounds/announcer_roy.wav", "sounds/announcer_wii_fit_trainer.wav", "sounds/announcer_chrom.wav", "sounds/announcer_hero.wav", "sounds/announcer_lucario.wav", "sounds/announcer_pac_man.wav", "sounds/announcer_ryu.wav", "sounds/announcer_wolf.wav", "sounds/announcer_cloud.wav", "sounds/announcer_ice_climbers.wav", "sounds/announcer_lucas.wav", "sounds/announcer_palutena.wav", "sounds/announcer_samus.wav", "sounds/announcer_yoshi.wav", "sounds/announcer_corrin.wav", "sounds/announcer_ike.wav", "sounds/announcer_lucina.wav", "sounds/announcer_peach.wav", "sounds/announcer_sephiroth.wav", "sounds/announcer_young_link.wav", "sounds/announcer_daisy.wav", "sounds/announcer_incineroar.wav", "sounds/announcer_luigi.wav", "sounds/announcer_pichu.wav", "sounds/announcer_sheik.wav", "sounds/announcer_zelda.wav", "sounds/announcer_dark_pit.wav", "sounds/announcer_inkling.wav", "sounds/announcer_mario.wav", "sounds/announcer_pikachu.wav", "sounds/announcer_shulk.wav", "sounds/announcer_zero_suit_samus.wav", "sounds/announcer_dark_samus.wav", "sounds/announcer_isabelle.wav", "sounds/announcer_marth.wav", "sounds/announcer_piranha_plant.wav", "sounds/announcer_simon.wav", "sounds/se_matchup_spritsboad.wav", "sounds/announcer_diddy_kong.wav", "sounds/announcer_jigglypuff.wav", "sounds/announcer_mega_man.wav", "sounds/announcer_pit.wav", "sounds/announcer_snake.wav", "sounds/announcer_donkey_kong.wav", "sounds/announcer_joker.wav", "sounds/announcer_meta_knight.wav", "sounds/announcer_pokemon_trainer.wav", "sounds/announcer_sonic.wav"];
let scripts = ["scripts/fighter.js", "scripts/script.js"];

self.addEventListener('install', e => {
    e.waitUntil(
        caches.open('bright-smash').then(cache => {
            return cache.addAll([
                "index.html",
                "fighters.json",
                ...images,
                ...sounds,
                ...scripts
            ]);
        })
    );
});
self.addEventListener('fetch', e => {
    // console.log(e.request.url);
    e.respondWith(
        caches.match(e.request).then(response => {
            return response || fetch(e.request);
        })
    );
});
